[pytest]
markers =
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests
    slow: marks tests as slow
    skip: skip test for specific reasons



addopts = --alluredir=reports/allure-results --clean-alluredir
